import DataBase_Management as DM

DM.Data_Deleting_FromDB.Delete_Tables.TBDaily_Delete_Daily_Historical_Tables_FORALL_Symbols()
DM.DB_Setup.Create_Tables.Create_TBDailyCandle_Historical_Databases_ForAll_Symbols()
DM.DB_Setup.Create_Tables.Create_TBDailyCandle_Historical_Prediction_Databases_ForAll_Symbols()
